Add information about minor versions within a subscribed API’s major version range
wso2/docs-choreo-dev pull request #1137
Opened 2023-10-04 04:09 UTC by Nashaath

## Purpose
Update content to include information that new API subscriptions cover all minor versions within the subscribed API’s major version range.

2023-10-05 06:12 UTC, shaniR requested changes

2023-10-05 09:38 UTC, Nashaath commented on en/docs/consuming-services/consuming-a-sevice.md
> +      If you want to use an API, the recommended approach is to use the latest version of it. You can copy the major version range pattern provided as the value of **Endpoints(s)** on the API overvie
+1
Done.

2023-10-05 09:38 UTC, Nashaath commented on en/docs/consuming-services/create-a-subscription.md
> +!!! info "What is a major version range?"
Done

2023-10-05 09:40 UTC, Nashaath commented on en/docs/consuming-services/create-a-subscription.md
> +          APIs can have multiple versions that belong to a common major version. For example, if you have API versions `v1.0`, `v1.1`, and `v1.2`, all of those fall under the major version range v1.
Removed the note.

2023-10-06 08:59 UTC, shaniR approved these changes

2023-10-06 08:59 UTC, merged