Improving the details about testing an org level endpoint
wso2/docs-choreo-dev pull request #1342
Opened 2024-02-14 08:45 UTC by amilam

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format:
I was going through the doc related to testing APIs and noticed these minor improvements.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

2024-02-14 08:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/docs-choreo-dev?pullRequest=1342) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/docs-choreo-dev?pullRequest=1342) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/docs-choreo-dev?pullRequest=1342) it.</sub>

2024-02-14 09:33 UTC, shaniR requested changes

2024-02-14 09:33 UTC, shaniR commented on en/docs/testing/test-rest-endpoints-via-the-openapi-console.md
> +   !!! note - The **Network Visibility** of an endpoint is set in the **endpoints.yaml**. You can set it to **Public**, **Organization**, or **Project**. - If you have set the **Network Visibility**
Inline with the [Google style guide](https://developers.google.com/style/abbreviations#dont-use), We don't use the abbrevation i.e. Instead we use "that is" or "for example"

2024-02-14 15:03 UTC, amilam commented on en/docs/testing/test-rest-endpoints-via-the-openapi-console.md
> +   !!! note - The **Network Visibility** of an endpoint is set in the **endpoints.yaml**. You can set it to **Public**, **Organization**, or **Project**. - If you have set the **Network Visibility**
Ack. I couldn't think of a better way to replace "i.e.". Hence slightly modified that part. Fixed the indentation which I wasn't aware to break the rendering. I have now locally built and verified rendering.

2024-02-14 15:03 UTC, amilam commented on en/docs/testing/test-rest-endpoints-via-the-openapi-console.md
> +   The temporary test URL will be available **only for 15 minutes** and it will get expired after. You can deactivate the test URL by clicking on the **Deactivate URL** button.
Fixed it.

2024-02-14 15:03 UTC, amilam commented on en/docs/testing/test-rest-endpoints-via-the-openapi-console.md
> +   ![OpenAPI Console](../assets/img/testing/openapi-console-org.png){.cInlineImage-full}
Fixed it.

2024-02-16 09:24 UTC, shaniR approved these changes

2024-02-16 17:15 UTC, merged