Add Config mount path for web apps
wso2/docs-choreo-dev pull request #1388
Opened 2024-03-13 10:31 UTC by Thushani-Jayasekera

## Purpose
> Relates to https://github.com/wso2-enterprise/choreodp-cicd/pull/1393

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

2024-03-15 05:51 UTC, shaniR requested changes

2024-03-15 05:51 UTC, shaniR commented on en/docs/quick-start-guides/configure-front-end-application-qsg.md
> +!!! note
Shall we rephrase it as "In static web applications, when a configuration file exists within the public folder of the source and shares the same name as the file mounted to the /app/public mount path, the latter file will take precedence over the one inside the public folder."

2024-03-29 11:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/docs-choreo-dev?pullRequest=1388) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wso2/docs-choreo-dev?pullRequest=1388) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: shaniR<br/>:x: Thushani-Jayasekera<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/docs-choreo-dev?pullRequest=1388) it.</sub>

2024-04-17 04:56 UTC, shaniR approved these changes

2024-05-02 05:58 UTC, Nashaath approved these changes

2024-05-02 05:58 UTC, merged