Remove Postman testing docs
wso2/docs-choreo-dev pull request #1395
Opened 2024-03-15 09:47 UTC by Suvink

## Purpose
$subject

Related to https://github.com/wso2-enterprise/choreo/issues/26305

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

2024-03-15 10:36 UTC, shaniR approved these changes

2024-03-15 10:36 UTC, shaniR requested changes

2024-03-15 10:36 UTC, shaniR commented on en/docs/testing/test-apis-using-postman.md
We need to remove from mkdocs.yaml too

2024-03-29 08:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/docs-choreo-dev?pullRequest=1395) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/docs-choreo-dev?pullRequest=1395) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/docs-choreo-dev?pullRequest=1395) it.</sub>

2024-03-29 08:03 UTC, Suvink commented on en/docs/testing/test-apis-using-postman.md
Fixed with [20f3fff](https://github.com/wso2/docs-choreo-dev/pull/1395/commits/20f3fff63be444a3433a87ca16ba118764e26355)

2024-03-29 08:08 UTC, shaniR approved these changes

2024-04-17 04:55 UTC, shaniR approved these changes

2024-05-02 06:30 UTC, Suvink commented
Converting to a draft since approach to remove this feature has been changed.

2024-06-10 04:38 UTC, Nashaath approved these changes

2024-06-10 04:39 UTC, merged